version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: python -m flask run --host=0.0.0.0 --port=5000 --reload

  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
